In [2]:
import torch

a = torch.randn(1, 5)
print(a)

tensor([[ 0.7226,  0.2451, -1.7216,  0.4556,  0.6064]])


In [3]:
b = torch.tensor([[0, 1, 2, 3, 0, 0, 4],
                    [5, 4, 0, 0, 2, 5, 7]])

print(torch.nonzero(b))

tensor([[0, 1],
        [0, 2],
        [0, 3],
        [0, 6],
        [1, 0],
        [1, 1],
        [1, 4],
        [1, 5],
        [1, 6]])


In [4]:
a = torch.nonzero(b)[:, 0]
print(a)

tensor([0, 0, 0, 0, 1, 1, 1, 1, 1])


In [5]:
c = torch.nonzero(b)[:, 1]
print(c)

tensor([1, 2, 3, 6, 0, 1, 4, 5, 6])


In [9]:
import torch.nn

d = torch.randn(10, 10)
e = torch.randn(10, 10)

print((torch.matmul(d, e)).shape)


torch.Size([10, 10])


In [21]:
f = torch.matmul(d, e)
# print(f.view(-1, 1))

print((e.unsqueeze(0)).shape)

torch.Size([1, 10, 10])


In [22]:
print((e.squeeze(1)).shape)

torch.Size([10, 10])


In [27]:
g = torch.randint(0, 3, (3, 4))

In [28]:
print(torch.reshape(g, (-1,)))

tensor([0, 1, 0, 0, 0, 0, 2, 0, 2, 1, 1, 2])


In [32]:
ltp = torch.reshape(g, (-1,))
print(ltp)

tensor([0, 1, 0, 0, 0, 0, 2, 0, 2, 1, 1, 2])


In [30]:
print(g)

tensor([[0, 1, 0, 0],
        [0, 0, 2, 0],
        [2, 1, 1, 2]])
