In [2]:
import torch

a = torch.randn(1, 5)
print(a)

tensor([[ 0.7226,  0.2451, -1.7216,  0.4556,  0.6064]])


In [3]:
b = torch.tensor([[0, 1, 2, 3, 0, 0, 4],
                    [5, 4, 0, 0, 2, 5, 7]])

print(torch.nonzero(b))

tensor([[0, 1],
        [0, 2],
        [0, 3],
        [0, 6],
        [1, 0],
        [1, 1],
        [1, 4],
        [1, 5],
        [1, 6]])


In [4]:
a = torch.nonzero(b)[:, 0]
print(a)

tensor([0, 0, 0, 0, 1, 1, 1, 1, 1])


In [5]:
c = torch.nonzero(b)[:, 1]
print(c)

tensor([1, 2, 3, 6, 0, 1, 4, 5, 6])
